#ifndef KEYS_H
#define KEYS_H

#define TOGGLESWITCH1KEY '0'
#define TOGGLESWITCH2KEY '1'
#define TOGGLESWITCH3KEY '2'
#define TOGGLESWITCH4KEY '3'

#define BUTTONRED1KEY '4'
#define BUTTONRED2KEY '5'
#define BUTTONRED3KEY '6'
#define BUTTONRED4KEY '7'

#define BUTTONBLACK1KEY '8'
#define BUTTONBLACK2KEY '9'
#define BUTTONBLACK3KEY 'a'
#define BUTTONBLACK4KEY 'b'

#define STARTKEYKEY 'c'
#define STARTTOGGLEKEY 'd'

#define R1CLOCKWISEKEY 'e'
#define R1COUNTERCLOCKWISEKEY 'f'
#define R1BUTTONPRESSKEY 'g'
#define R2CLOCKWISEKEY 'e'
#define R2COUNTERCLOCKWISEKEY 'f'
#define R2BUTTONPRESSKEY 'g'
#define R3CLOCKWISEKEY 'e'
#define R3COUNTERCLOCKWISEKEY 'f'
#define R3BUTTONPRESSKEY 'g'
#define R4CLOCKWISEKEY 'e'
#define R4COUNTERCLOCKWISEKEY 'f'
#define R4BUTTONPRESSKEY 'g'

#endif