#ifndef PINOUT_H
#define PINOUT_H

#define TOGGLESWITCH1PIN 2
#define TOGGLESWITCH2PIN 4
#define TOGGLESWITCH3PIN 5
#define TOGGLESWITCH4PIN 18

#define BUTTONREDSERIEPIN 34
#define BUTTONBLACKSERIEPIN 35

#define STARTKEYPIN 19
#define STARTTOGGLEPIN 21

#define ROTARYENCODER1APIN 4
#define ROTARYENCODER1BPIN 23
#define ROTARYENCODER2APIN 4
#define ROTARYENCODER2BPIN 23
#define ROTARYENCODER3APIN 4
#define ROTARYENCODER3BPIN 23
#define ROTARYENCODER4APIN 4
#define ROTARYENCODER4BPIN 23

#endif